import Image from 'next/image';
import Link from 'next/link';
import { siteConfig } from '@/config/site';

export const dynamic = 'force-static';

const galleryItems = [
    {
        src: '/examples/tiktok-live-stream.png',
        title: 'TikTok live stream mockup',
        titleZh: 'TikTok 直播界面示例',
        alt: 'A TikTok live stream style portrait mockup generated with GPT Image 2, vertical mobile UI with comments and reactions',
        altZh: '使用 GPT Image 2 生成的 TikTok 直播界面风格人像示例，竖屏移动端布局，带评论和互动按钮',
        prompt: 'Generate a screenshot of a TikTok live stream featuring a beautiful woman streaming.',
        promptZh: '生成一张 TikTok 直播截图，画面是一位漂亮女生正在直播。',
    },
    {
        src: '/examples/design-system-board.png',
        title: 'Design system board',
        titleZh: '设计系统展示板',
        alt: 'A clean SaaS design system board generated with GPT Image 2, including buttons, cards, inputs, desktop pages, and mobile screens',
        altZh: '使用 GPT Image 2 生成的 SaaS 设计系统展示板，包含按钮、卡片、输入框、桌面页面和移动端界面',
        prompt: 'Generate a UI design system for me in xx style, including web pages, mobile, cards, controls, buttons, and others.',
        promptZh: '请用 xx 风格为我生成一套 UI design system，包括 Web 页面、移动端、卡片、控件、按钮等。',
    },
    {
        src: '/examples/cyberpunk-silver-portrait.png',
        title: 'Cyberpunk silver portrait',
        titleZh: '赛博朋克银发人像',
        alt: 'A cyberpunk style silver hair portrait generated by GPT Image 2, neon reflections, rainy city night, metallic jacket and glowing face implants',
        altZh: '使用 GPT Image 2 生成的赛博朋克银发人像，带霓虹反射、雨夜城市、金属外套和发光面部植入物',
        prompt: 'A close-up portrait of a woman with short silver hair in a rain-soaked cyberpunk city at night. Neon signs in pink and teal reflect off wet surfaces and her metallic jacket. Futuristic face implants glow softly beneath the skin. Shot with a wide-aperture lens, bokeh of city lights in the background.',
        promptZh: '一位短银发女性的近景人像，站在雨夜赛博朋克城市中。粉色和青绿色霓虹招牌倒映在潮湿地面与她的金属感外套上，皮肤下若隐若现的未来感面部植入物柔和发光。使用大光圈镜头拍摄，背景是城市灯光形成的散景。',
    },
    {
        src: '/examples/pixel-ramen-shop.png',
        title: 'Retro pixel ramen shop',
        titleZh: '复古像素拉面店',
        alt: 'A retro pixel art ramen shop scene generated with GPT Image 2, rainy Japanese alley, glowing neon ramen sign, cozy window light and a cat under the awning',
        altZh: '使用 GPT Image 2 生成的复古像素拉面店场景，雨夜日本小巷、发光拉面招牌、温暖店窗灯光和躲雨的猫',
        prompt: 'A retro pixel art scene of a cozy ramen shop on a rainy night in a quiet Japanese alley. Warm light spills from the shop window, a cat sits under the awning, steam rises from a bowl visible through the glass. 16-bit color palette, detailed pixel work for rain droplets, neon sign glows \'ラーメン\'. Nostalgic and atmospheric.',
        promptZh: '一个复古像素风场景：安静的日本小巷里，一家温馨的拉面店正处在雨夜中。暖黄灯光从店窗溢出，一只猫蹲在雨棚下，透过玻璃能看到冒着热气的拉面。使用 16-bit 配色，雨滴像素细节丰富，霓虹招牌写着“ラーメン”，整体怀旧而有氛围。',
    },
];

export async function generateMetadata(props: { params: Promise<{ locale: string }> }) {
    const params = await props.params;
    const { locale } = params;
    const isZh = locale === 'zh';

    const title = isZh ? 'GPT Image 2 示例画廊' : 'GPT Image 2 Gallery';
    const description = isZh
        ? '浏览 GPT Image 2 生成的海报、人像、设计系统和像素艺术示例，查看提示词与成品效果。'
        : 'Browse GPT Image 2 examples for portraits, posters, design systems, and pixel art, with prompt references and finished visuals.';

    return {
        title,
        description,
        alternates: {
            canonical: `${siteConfig.url}/${locale}/gallery`,
            languages: {
                en: `${siteConfig.url}/en/gallery`,
                zh: `${siteConfig.url}/zh/gallery`,
                'x-default': `${siteConfig.url}/en/gallery`,
            },
        },
        openGraph: {
            title,
            description,
            type: 'website',
            url: `${siteConfig.url}/${locale}/gallery`,
        },
        twitter: {
            title,
            description,
        },
    };
}

export default async function GalleryPage(props: { params: Promise<{ locale: string }> }) {
    const params = await props.params;
    const { locale } = params;
    const isZh = locale === 'zh';
    const localePrefix = `/${locale}`;

    return (
        <div className="min-h-screen bg-[linear-gradient(180deg,#fffaf4_0%,#fff7ee_48%,#fffdf9_100%)]">
            <div className="container px-4 py-16 md:px-6">
                <div className="mx-auto max-w-6xl">
                    <div className="text-center">
                        <p className="text-sm font-semibold uppercase tracking-[0.2em] text-orange-600">
                            {isZh ? '示例画廊' : 'Gallery'}
                        </p>
                        <h1 className="mt-4 text-4xl font-bold tracking-tight text-slate-900 sm:text-5xl">
                            {isZh ? '看看 GPT Image 2 可以生成的不同画面方向' : 'See the kinds of visuals GPT Image 2 can create'}
                        </h1>
                        <p className="mx-auto mt-4 max-w-3xl text-lg leading-8 text-slate-600">
                            {isZh
                                ? '这里集中展示了人物、人像、设计系统、像素艺术等不同风格的示例图，并附上提示词，方便你直接参考或继续改写。'
                                : 'This gallery collects portraits, UI boards, pixel art, and other example outputs, each paired with a prompt you can study or adapt.'}
                        </p>
                    </div>

                    <div className="mt-12 grid gap-8 md:grid-cols-2">
                        {galleryItems.map((item) => (
                            <article key={item.src} className="overflow-hidden rounded-[28px] border border-orange-100 bg-white shadow-[0_20px_50px_rgba(235,145,71,0.08)]">
                                <div className="relative aspect-[4/3] bg-[#fff6ee]">
                                    <Image
                                        src={item.src}
                                        alt={isZh ? item.altZh : item.alt}
                                        fill
                                        className="object-cover"
                                    />
                                </div>
                                <div className="p-6">
                                    <h2 className="text-2xl font-bold text-slate-900">
                                        {isZh ? item.titleZh : item.title}
                                    </h2>
                                    <p className="mt-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                                        Prompt
                                    </p>
                                    <p className="mt-3 leading-8 text-slate-700">
                                        {isZh ? item.promptZh : item.prompt}
                                    </p>
                                </div>
                            </article>
                        ))}
                    </div>

                    <div className="mt-12 text-center">
                        <Link
                            href={`${localePrefix}/create`}
                            className="inline-flex items-center justify-center rounded-full bg-[#ff6b2c] px-8 py-4 text-lg font-semibold text-white shadow-[0_18px_36px_rgba(255,107,44,0.24)] transition-colors hover:bg-[#f86120]"
                        >
                            {isZh ? '进入生成器开始创作' : 'Open the generator'}
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
